import { Inter } from "next/font/google";
import "/styles/mixins/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LandingPage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
